config/routes.rb
require 'sidekiq/web'

Archivizer::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web, at: '/sidekiq'

  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#big_thumb_570x200', constraints: { filename: /big_thumb_570x200.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#big_thumb_270x430', constraints: { filename: /big_thumb_270x430.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#big_thumb_270x200', constraints: { filename: /big_thumb_270x200.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#big_thumb_270x170', constraints: { filename: /big_thumb_270x170.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#big_thumb_538x435', constraints: { filename: /big_thumb_538x435.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#big_thumb_file', constraints: { filename: /big_thumb.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#mini_thumb_24x24', constraints: { filename: /mini_thumb_24x24.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#mini_thumb_30x30', constraints: { filename: /mini_thumb_30x30.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#mini_thumb_70x70', constraints: { filename: /mini_thumb_70x70.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#middle_thumb_173x182', constraints: { filename: /middle_thumb_173x182.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#middle_thumb_142x163', constraints: { filename: /middle_thumb_142x163.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#middle_thumb_182x182', constraints: { filename: /middle_thumb_182x182.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#middle_thumb', constraints: { filename: /middle_thumb.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#thumb_file', constraints: { filename: /thumb.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#full_screen_thumb_1000x850', constraints: { filename: /full_screen_thumb_1000x850.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#full_screen_thumb', constraints: { filename: /full_screen_thumb.*/ }
  match '/uploads/grid/uploads/:model/file/:id/:filename' => 'gridfs#file', constraints: { filename: /.*/ }

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords", :confirmations => "confirmations"}

  resources :search, :only => [:index, :show] do
    collection do
      post "index"
    end
  end

  resources :feed_backs, :path => "feed-back", :only => [:create] do
    post 'subscribe', :on => :collection
  end

  resources :faqs, :only => [:index], :path => 'faq'
  resources :people, :only => [:index]
  resources :reviews, :only => [:index]
  resources :pages, :only => [:show]
  resources :portfolios,  :only => [:index, :show], :path => 'portfolio' do
    get 'page/:page', :action => :index, :on => :collection
    get 'page/:page', :action => :show, :on => :member
  end
  resources :articles, :only => [:show]
  #resources :testings # Only for debugging

  namespace :api do

    resources :feed_backs, :path => "feed-back"
    resources :settings, :only => [:index, :show, :create, :update]
    resources :users do
      resources :inbox_messages, :path => "inbox-messages"
      resources :sent_messages, :path => "sent-messages"
      collection do
        get "blocked"
        get 'current'
      end
    end
    resources :user_ids, :path => "user-ids", :only => [:show, :destroy]

    resources :roles
    resources :permissions

    resources :translations, :only => [:index, :create] do
      collection do
        get "dump"
        post "import"
      end
    end
    resources :blocks do
      collection do
        get "blocked"
      end
    end
    resources :block_ids, :path => "block-ids", :only => [:show, :destroy]

    resources :sections do
      resources :categories
      member do
        get 'root_categories', :path => "root-categories"
        post 'rebuild'
      end
    end
    resources :menus do
      resources :links
      member do
        post 'rebuild'
      end
    end

    resources :faqs
    resources :people
    resources :comments
    resources :slides
    resources :portfolios
    resources :images
    resources :static_images, :path => 'static-images'
    resources :person_images, :path => 'person-images'
    resources :slideshow_images, :path => 'slideshow-images'
    resources :file_attachments
    resources :result_file_attachments
    resources :max_files
    resources :sample_project_styles
    resources :furniture_plans
    resources :ceiling_plans
    resources :lighting_plans
    resources :coverings_plans
    resources :coverings_textures
    resources :walls_plans
    resources :walls_textures
    resources :selected_facilities do
      collection do
        post 'empty'
      end
    end
    resources :selected_facility_textures
    resources :selected_scenes do
      collection do
        post 'empty'
      end
    end
    resources :selected_scene_textures
    resources :modeling_tasks
    resources :modeling_task_images
    resources :modeling_task_textures

    resources :sketches  do
      collection do
        get "blocked"
      end
    end
    resources :sketch_ids, :path => "sketch-ids", :only => [:show, :destroy]

    resources :reviews  do
      collection do
        get "blocked"
      end
    end
    resources :review_ids, :path => "review-ids", :only => [:show, :destroy]

    resources :discounts  do
      collection do
        get "blocked"
      end
    end
    resources :discount_ids, :path => "discount-ids", :only => [:show, :destroy]

    resources :nodes
    resources :pages  do
      collection do
        get "blocked"
      end
    end
    resources :page_ids, :path => "page-ids", :only => [:show, :destroy]
    resources :articles  do
      collection do
        get "blocked"
      end
    end
    resources :article_ids, :path => "article-ids", :only => [:show, :destroy]

    resources :facilities  do
      collection do
        get "blocked"
      end
    end
    resources :facility_ids, :path => "facility-ids", :only => [:show, :destroy]

    resources :scenes  do
      collection do
        get "blocked"
      end
    end
    resources :scene_ids, :path => "scene-ids", :only => [:show, :destroy]

    resources :facilities_sets, :path => "facilities-sets" do
      member do
        get "zip"
      end
    end
    resources :scenes_sets, :path => "scenes-sets" do
      member do
        get "zip"
      end
    end
    resources :tasks do
      resources :discussions
      member do
        get "zip"
        get "file_attachments_zip"
        get "result_file_attachments_zip"
        get "selected_facilities_zip"
        get "selected_scenes_zip"
        post "set"
        post "toggle_selected"
      end
    end

    resources :discussion_messages

    resources :projects  do
      collection do
        get "blocked"
      end
    end
    resources :project_ids, :path => "project-ids", :only => [:show, :destroy]

    resources :visualizations  do
      collection do
        get "blocked"
      end
      member do
        get "zip"
        get "sketch"
        post "order"
      end
    end
    resources :visualization_ids, :path => "visualization-ids", :only => [:show, :destroy]

  end

  match 'account', to: 'account#index'
  match 'account/*path', to: 'account#index'
  match 'admin', to: 'admin#index'
  match 'admin/*path', to: 'admin#index'

  get 'task_set', :to => 'welcome#task_set'
  get 'about', :to => 'welcome#about'
  get 'service', :to => 'welcome#service'
  get 'sitemap(.:format)', to: 'welcome#sitemap'
  get 'robots(.:format)', to: 'welcome#robots'
  get 'login', :to => 'welcome#login'
  get 'client-register', :to => 'welcome#client_register'
  get 'worker-register', :to => 'welcome#worker_register'

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < BaseCrudController

  def initialize
    @model = Page
    super
  end

  def index

    respond_to do |format|
      format.html
    end
  end

  def service
    gon.roomSpaceLessThen = Settings.room_space_less_then
    gon.roomSpaceLessValue = Settings.room_space_less_value
    gon.roomSpaceAboveValue = Settings.room_space_above_value

    gon.discountLessThen = Settings.discount_less_then
    gon.discountLessValue = Settings.discount_less_value
    gon.discountAboveValue = Settings.discount_above_value

    gon.urgency1Day = Settings.urgency_1_day
    gon.urgency2Day = Settings.urgency_2_day
    gon.urgency3Day = Settings.urgency_3_day
    gon.urgency4Day = Settings.urgency_4_day

    gon.furniturePlanCost = Settings.furniture_plan_cost
    gon.ceilingPlanCost = Settings.ceiling_plan_cost
    gon.lightingPlanCost = Settings.lighting_plan_cost
    gon.coveringsPlanCost = Settings.coverings_plan_cost
    gon.wallsPlanCost = Settings.walls_plan_cost

    gon.selectingFacilitiesCost = Settings.selecting_facilities_cost

    gon.adjustmentsCountLessThen = Settings.adjustments_count_less_then
    gon.adjustmentsCountLessValue = Settings.adjustments_count_less_value
    gon.adjustmentsCountAboveValue = Settings.adjustments_count_above_value

    gon.modelingTasksCost = Settings.modeling_tasks_cost
    gon.highValueImageCost = Settings.high_value_image_cost
    gon.initialSceneCost = Settings.initial_scene_cost
    gon.highResolutionImageCost = Settings.high_resolution_image_cost
    gon.drawingsCost = Settings.drawings_cost

    respond_to do |format|
      format.html
    end
  end

  def about
    @body_class = 'about'
  end

  def sitemap
    @records = Node.in_xml_sitemap
    @map = XmlSitemap::Map.new(Settings.hostname) do |m|
      @records.each do |record|
        m.add polymorphic_path(record)
      end
    end

    respond_to do |format|
      format.xml { render :xml => @map.render }
      format.json { render :json => Hash.from_xml(@map.render).to_json }
      format.html
    end
  end

  def robots
    respond_to do |format|
      format.txt { render :text => Settings.robots_txt }
    end
  end

  def login
    redirect_to new_user_session_path
  end

  def client_register

  end

  def worker_register

  end

  def task_set
    redirect_to root_path, notice: I18n.t("models.tasks.created")
  end


  protected

  def per_records
    Settings.main_page_records_count.to_i || 20
  end

  def get_index_title
    @title = Settings.main_page_title
  end

  def get_index_keywords
    @seo_keywords = Settings.main_page_keywords
  end

  def get_index_description
    @seo_description = Settings.main_page_description
  end

  def get_index_robots
    @seo_robots = Settings.main_page_robots
  end

end

app/views/welcome/about.html.erb
<%= render :partial => 'shared/about_tabs' %>

<div class="about">
  <div id="tab1" class="content">
    <h1>Студия архитектурной визуализации ARCHIVIZER</h1>
    <p>Archivizer  - сервис  по созданию визуализации и дизайна интерьера. Мы поможем вам подать любые идеи в выгодном свете</p>
    <div class="visual"><img src="<%= asset_path('img44.jpg') %>" alt="image description" width="871" height="408"></div>
    <!-- twocolumns box -->
    <div class="content-wrapper">
      <div class="twocolumns">
        <div class="col">
          <h2>Делаем идеи наглядными</h2>
          <p>Наша 3d студия всегда ставит перед собой непростую задачу – превратить заказчика в довольного клиента, поэтому качество является основным приоритетом. Мы любим свою работу и привыкли выкладываться на все 100%. Искусство – неотъемлемая часть нашей работы. Мы не просто выполняем техническое задание, а вносим творческую составляющую в каждый проект.</p>
          <!-- contacts info -->
          <address>
            <dl>
              <dt>Дата создания: </dt>
              <dd><time datetime="2008-06-25">25/06/2008</time></dd>
            </dl>
            <dl>
              <dt>Email: </dt>
              <dd><a href="mailto:sales@archivizer.com">sales@archivizer.com</a></dd>
              <dt>Skype: </dt>
              <dd><a href="skype:archivizer.com?chat">archivizer.com</a></dd>
              <dt>Телефон: </dt>
              <dd>+38066-342-0000</dd>
            </dl>
          </address>
        </div>
        <div class="col">
          <h2>Наша специализация</h2>
          <!-- box line -->
          <div class="box-line">
            <p><strong>Визуализация и моделирование</strong> 100%</p>
            <span class="line"> </span>
            <p><strong>Дизайн интерьера</strong> 75%</p>
            <span class="line line-1"> </span>
            <p><strong>Проектирование</strong> 25%</p>
            <span class="line line-2"> </span>
            <p><strong>Архитектура</strong> 50%</p>
            <span class="line line-3"> </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/client_register.html.slim
.wrapper
  = simple_form_for(resource, :as => resource_name, :validate => true, :url => registration_path(resource_name), :html => {:class => "form-signin login-form"}) do |f|
    - if resource.errors.any?
      - @form_errors = resource
    h2.form-signin-heading = I18n.t("login.links.registration")
    .text
      = render :partial => "fields/forms/name", :locals => {:f => f, placeholder: I18n.t("words.your_name")}
    .text.email-field
      = render :partial => "fields/forms/email", :locals => {:f => f, :placeholder => I18n.t('words.inputs.email')}
    = render :partial => 'auth/links', :locals => {:do_ajax => true, :view_links => %w(sign_in forgot do_not_receive)} if defined?(do_ajax)
    = render :partial => 'auth/links', :locals => {:view_links => %w(sign_in forgot do_not_receive)} unless defined?(do_ajax)
    = render :partial => "fields/forms/submit", :locals => {:f => f, :field_value => I18n.t('words.register'), :field_class => "close register"}

app/views/welcome/index.html.slim
= render :partial => 'blocks/register'
= render :partial => 'blocks/services'
= render :partial => 'blocks/discover'
= render :partial => 'blocks/advantages'
= render :partial => 'blocks/feature'
= render :partial => 'blocks/reviews'

app/views/welcome/service.html.slim
= render :partial => 'blocks/calculator'
= render :partial => 'blocks/steps'
= render :partial => 'blocks/design'
= render :partial => 'blocks/scheme'
= render :partial => 'blocks/modeling'

app/views/welcome/worker_register.html.slim
.wrapper
  = simple_form_for(resource, :as => resource_name, :validate => true, :url => registration_path(resource_name), :html => {:class => "form-signin login-form"}) do |f|
    - if resource.errors.any?
      - @form_errors = resource
    h2.form-signin-heading = I18n.t("login.links.registration")
    .text
      = render :partial => "fields/forms/name", :locals => {:f => f, placeholder: I18n.t("words.your_name")}
    .text.email-field
      = render :partial => "fields/forms/email", :locals => {:f => f, :placeholder => I18n.t('words.inputs.email')}
    input type="hidden" name="role" value="worker"
    = render :partial => 'auth/links', :locals => {:do_ajax => true, :view_links => %w(sign_in forgot do_not_receive)} if defined?(do_ajax)
    = render :partial => 'auth/links', :locals => {:view_links => %w(sign_in forgot do_not_receive)} unless defined?(do_ajax)
    = render :partial => "fields/forms/submit", :locals => {:f => f, :field_value => I18n.t('words.register'), :field_class => "close register"}